"""Add progress and error_message fields to tasks

Revision ID: bf296fc8b9f3
Revises: 2609822d179d
Create Date: 2026-03-01 14:36:19.752098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf296fc8b9f3'
down_revision = '2609822d179d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('progress', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'error_message')
    op.drop_column('tasks', 'progress')
    # ### end Alembic commands ###